CREATE TABLE IF NOT EXISTS empresas(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    nome VARCHAR(255) NOT NULL,
    cnpj VARCHAR(14) UNSIGNED,
    PRIMARY KEY (id),
    UNIQUE KEY (cnpj)
);

-- COMO EXISTE UMA RELAÇÃO DE MUITOS PARA MUITOS,
-- SERÁ CRIADO UMA TERCEIRA TABELA QUE POSSUI A RELAÇÃO ENTRE `cidades` E `empresas`

CREATE TABLE IF NOT EXISTS empresas_unidades (
    empresa_id INT UNSIGNED NOT NULL,
    cidade_id INT UNSIGNED NOT NULL,
    -- INDICA APENAS UM UNICO VALOR. CASO SEJA SEDE OU NÃO
    sede TINYINT(1) NOT NULL,
    PRIMARY KEY (empresa_id, cidade_id)
);