-- 'UNIQUE KEY' DEFINE QUE A RELAÇÃO SERÁ UM PARA UM.
-- OU SEJA, VINCULADO A UM PREFEITO SÓ TERÁ UMA CIDADE.
CREATE TABLE IF NOT EXISTS prefeitos(
    id INT NOT NULL AUTO_INCREMENT,
    nome VARCHAR(255) NOT NULL,
    cidade_id INT UNSIGNED,
    PRIMARY KEY (id),
    UNIQUE KEY (cidade_id),
    FOREIGN KEY (cidade_id) REFERENCES cidades (id)
);